### ISSUE TITLE
Error opening taxi.csv (from the website download page)

### ISSUE THREAD

**Issue by yoid2000** [diffix/dashboards#128]
Damian reports this:

I couldn´t import the taxi sample CSV: Data "import failed: Error: Error invoking remote method 'import_csv': TypeError: Cannot read property 'stream' of null"

I had the same problem.

**Comment by cristianberneanu** [comment]
You need to delete the row containing `\n`. We don't yet handle this marker for NULL.

**Comment by yoid2000** [comment]
ok, I've taken care of it in the desktop repo. There is apull request there...
