### ISSUE TITLE
Opening a new Metabase tab while the Metabase service is starting results in an empty tab.

### ISSUE THREAD

**Issue by cristianberneanu** [diffix/dashboards#151]
Maybe we should wait until the service has finished starting before opening the page URL?

**Comment by pdobacz** [comment]
Related to #122?

**Comment by cristianberneanu** [comment]
Yes, related, although I was thinking of waiting for the start to finish instead of disabling the button.
Should I close it as redundant or do you think there is value in handling service error different from pending start?

**Comment by pdobacz** [comment]
Handling the case when the user operates within previously opened MB tab, while MB is down, deserves an issue (low priority).

But I guess opening a new Metabase tab should just be disabled, if the service is not running. It's all done from the Admin Tab, where the MB state is visible. Letting the user navigate away from there, just to show them another spinner may not be worth the extra code.
