### ISSUE TITLE
Making Metabase full screen breaks layout

### ISSUE THREAD

**Issue by edongashi** [diffix/dashboards#166]
In a Metabase dashboard, you have the option of viewing it in full screen. If toggled, it does not respect view height and shows everything in a thin strip at the top.

**Comment by pdobacz** [comment]
It works for me, looks like this: 
![Screenshot from 2022-12-12 18-06-00](https://user-images.githubusercontent.com/5735525/207108567-6f754ea7-37ae-4a7c-8fe8-772c2f96c8e3.png)

**Comment by edongashi** [comment]
Hmm, it's working for me as well now. Not sure how I ran into the issue...

**Comment by pdobacz** [comment]
ok let's reopen when it happens again for someone
